version: 0.2

env:
  variables:
    # テスト対象のアプリケーションURL（デプロイ後のURL）
    #TARGET_URL: "https://todolist-sample.com"
    # Playwrightの設定
    PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"
    # HTMLレポートを生成した後にブラウザを自動で起動しない
    PLAYWRIGHT_HTML_REPORT_OPEN: "0"
    # CIモードを強制的に有効にする
    CI: "1"
    # レポート保存用のS3バケット名
    REPORT_S3_BUCKET: "playwright-reports-v1"
  # secrets-manager:
    # 必要に応じて認証情報などを追加（今は特になし）

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing test dependencies"
      - echo "Setting up Playwright"
      
      # システム依存関係をインストール
      - apt-get update
      - apt-get install -y libgbm-dev libxkbcommon-x11-0 libgtk-3-0 libasound2 libx11-xcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 libglib2.0-0 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libatspi2.0-0 libxcursor1 libxi6 libxtst6 libpango-1.0-0 libcairo2
      
      # プロジェクトの依存関係をインストール
      - npm install
      
      # Playwrightのブラウザとシステム依存関係をインストール
      - npx playwright install chromium --with-deps || echo "Playwright browser installation failed, continuing anyway"

  pre_build:
    commands:
      - echo "Test preparation started on `date`"
      - echo "Checking connectivity to target application"
      #- curl -s -o /dev/null -w "%{http_code}" $TARGET_URL || echo "Warning: Target application may not be available"
      - echo "Setting exit code handling to continue on test failures"
      - set +e  # コマンドが失敗してもスクリプトの実行が継続される

  build:
    commands:
      - echo "Tests started on `date`"
      
      # E2Eテスト（Playwright）の実行
      - echo "Running E2E tests with Playwright"
      # CodeBuildはヘッドレス環境のため、--headedオプションは削除
      # dot,htmlレポーターを使用してHTMLレポートを生成しつつ、サーバーの起動を防止
      #- npx playwright test --workers=1 tests/testScenario.spec.ts --reporter=dot,html --update-snapshots || true
      - npx playwright test --workers=1 tests/testScenario.spec.ts --reporter=html || true
      - echo "E2E tests completed"

  post_build:
    commands:
      - echo "Tests completed on `date`"
      - set -e  # 通常の終了コード処理に戻す
      - echo "Generating test summary"
      
      # playwright-report/dataディレクトリ内のファイルを詳細に確認
      - echo "Checking files in playwright-report/data directory:"
      - find playwright-report/data -type f -exec file {} \; || echo "No files found in playwright-report/data"
      
      # S3にアップロード
      - echo "Uploading reports to S3"
      - REPORT_FOLDER=playwright_report_$(date +%Y%m%d_%H%M%S)

reports:
  e2e-reports:
    files:
      - playwright-report/index.html
    file-format: HTML
    base-directory: .

artifacts:
  files:
    - playwright-report/**/*
  name: playwright-report-$CODEBUILD_BUILD_ID
  base-directory: .
  discard-paths: no
