version: 0.2

env:
  variables:
    # テスト対象のアプリケーションURL（デプロイ後のURL）
    TARGET_URL: "https://todolist-sample.com"
    # Playwrightの設定
    PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"
  # secrets-manager:
    # 必要に応じて認証情報などを追加（今は特になし）

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing test dependencies"
      # - pip install --user pytest pytest-html locust coverage jinja2
      # - export PATH=$PATH:$HOME/.local/bin
      - echo "Setting up Playwright"
      
      # プロジェクトの依存関係をインストール
      - npm ci
      
      # Playwrightのブラウザをインストール
      - npx playwright install chromium

  pre_build:
    commands:
      - echo "Test preparation started on `date`"
      - echo "Checking connectivity to target application"
      - curl -s -o /dev/null -w "%{http_code}" $TARGET_URL || echo "Warning: Target application may not be available"
      - echo "Setting exit code handling to continue on test failures"
      - set +e  # コマンドが失敗してもスクリプトの実行が継続される

  build:
    commands:
      - echo "Tests started on `date`"

      # 負荷テスト（パフォーマンステスト）の実行
      # - echo "Running performance tests"
      # - locust -f tests/performance/locustfile.py --headless -u 10 -r 2 -t 1m --html=performance_report.html --host=$TARGET_URL || true
      # - echo "Performance tests completed"
      
      # E2Eテスト（Playwright）の実行
      - echo "Running E2E tests with Playwright"
      - npx playwright test tests/testScenario.spec.ts --reporter=html --output=playwright-report || true
      - echo "E2E tests completed"

  post_build:
    commands:
      - echo "Tests completed on `date`"
      - set -e  # 通常の終了コード処理に戻す
      - echo "Generating test summary"
      
      # S3バケットにレポートをアップロード
      # - aws s3 cp performance_report.html s3://$REPORT_S3_BUCKET/performance/performance_report_$(date +%Y-%m-%d_%H-%M-%S).html || true
      - aws s3 cp --recursive playwright-report s3://$REPORT_S3_BUCKET/e2e/playwright_report_$(date +%Y-%m-%d_%H-%M-%S)/ || true
      - echo "Test reports uploaded to S3"

reports:
  #performance-reports:
  #  files:
  #    - performance_report.html
  #  file-format: HTML
  #  base-directory: .
  e2e-reports:
    files:
      - playwright-report/index.html
    file-format: HTML
    base-directory: .

artifacts:
  files:
    #- performance_report.html
    - playwright-report/**/*
  discard-paths: yes
