version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  
  pre_build:
    commands:
      - echo "Starting Playwright tests..."
  
  build:
    commands:
      - npm test
  
  post_build:
    commands:
      - echo "Tests completed on `date`"
      - aws s3 cp ./playwright-report s3://$REPORT_S3_BUCKET/reports/$(date +%Y-%m-%d)/ --recursive

reports:
  playwright-reports:
    files:
      - "playwright-report/**/*"
    base-directory: "."
    file-format: "JunitXml"

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*
  base-directory: "."